//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WhatIsEF
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class SchooldbEntities : DbContext
    {
        public SchooldbEntities()
            : base("name=SchooldbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Course> Courses { get; set; }
        public virtual DbSet<SC> SCs { get; set; }
        public virtual DbSet<Student> Students { get; set; }
        public virtual DbSet<SC_Details> SC_Details { get; set; }
    
        public virtual ObjectResult<Get_Student_Result> Get_Student(string sno)
        {
            var snoParameter = sno != null ?
                new ObjectParameter("Sno", sno) :
                new ObjectParameter("Sno", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Get_Student_Result>("Get_Student", snoParameter);
        }
    }
}
